version: 2
updates:
  # Actualiza dependencias de npm (package.json y package-lock.json)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    ignore:
      - dependency-name: 'prisma'
        versions: ['<6.0.0'] # Ejemplo: ignora versiones antiguas de prisma

  # Actualiza acciones de GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 5
