// eslint.config.js
// Generated by Copilot
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
  {
    files: ['**/*.js', '**/*.ts'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      ...js.configs.recommended.rules,
    },
    plugins: {
      prettier,
    },
    env: {
      node: true,
    },
  },
];
