/* eslint-disable no-undef */
// Generated by Copilot
/* eslint-disable no-console */
// Este archivo contiene el script para hacer seed de la base de datos con Prisma usando ES Modules.

import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Iniciando seed de la base de datos...');

  // Agrega aquí tus datos de seed
  // Por ejemplo:
  const usuario = await prisma.usuario.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      nombre: 'Administrador',
      passwordHash: 'hashedpassword123',
      role: 'ADMIN',
    },
  });

  console.log('✅ Seed completado exitosamente');
  console.log({ usuario });
}

main()
  .catch((e) => {
    console.error('❌ Error durante el seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    console.log('🔌 Conexión a la base de datos cerrada');
  });
