// Generated by Copilot
const request = require('supertest');
const app = require('../index');

describe('API E2E', () => {
  it('GET / should return status 200', async () => {
    const res = await request(app).get('/');
    expect(res.statusCode).toBe(200);
    expect(res.text).toContain('API de Facturación Autónomos');
  });
});
