// Generated by Copilot
const request = require('supertest');
const app = require('../index');

describe('Clientes API E2E', () => {
  it('GET /clientes debe responder 200 y un array', async () => {
    const res = await request(app).get('/clientes');
    expect(res.statusCode).toBe(200);
    expect(Array.isArray(res.body)).toBe(true);
  });
});
