// Generated by Copilot
const prisma = require('../prisma/client');

// Función para manejar errores comunes
const handleError = (error, res, next) => {
  if (error.code === 'P2025') {
    return res.status(404).json({ error: 'Cliente no encontrado' });
  }
  next(error);
};

// Validar ID
const validateId = (id, res) => {
  const parsedId = Number(id);
  if (isNaN(parsedId)) {
    res.status(400).json({ error: 'ID inválido' });
    return null;
  }
  return parsedId;
};

// Obtener todos los clientes
exports.getAll = async (req, res, next) => {
  try {
    const clientes = await prisma.cliente.findMany();
    res.json(clientes);
  } catch (error) {
    handleError(error, res, next);
  }
};

// Obtener un cliente por ID
exports.getById = async (req, res, next) => {
  const id = validateId(req.params.id, res);
  if (!id) return;

  try {
    const cliente = await prisma.cliente.findUnique({ where: { id } });
    if (!cliente) {
      return res.status(404).json({ error: 'Cliente no encontrado' });
    }
    res.json(cliente);
  } catch (error) {
    handleError(error, res, next);
  }
};

// Crear un nuevo cliente
exports.create = async (req, res, next) => {
  try {
    const nuevoCliente = await prisma.cliente.create({ data: req.body });
    res.status(201).json(nuevoCliente);
  } catch (error) {
    handleError(error, res, next);
  }
};

// Actualizar un cliente
exports.update = async (req, res, next) => {
  const id = validateId(req.params.id, res);
  if (!id) return;

  try {
    const clienteActualizado = await prisma.cliente.update({
      where: { id },
      data: req.body,
    });
    res.json(clienteActualizado);
  } catch (error) {
    handleError(error, res, next);
  }
};

// Eliminar un cliente
exports.delete = async (req, res, next) => {
  const id = validateId(req.params.id, res);
  if (!id) return;

  try {
    await prisma.cliente.delete({ where: { id } });
    res.status(204).send();
  } catch (error) {
    handleError(error, res, next);
  }
};
