// Generated by Copilot
const prisma = require('../prisma/client');

// Obtener todas las facturas
exports.getAll = async (req, res, next) => {
  try {
    const facturas = await prisma.factura.findMany();
    res.json(facturas);
  } catch (error) {
    next(error);
  }
};

// Obtener una factura por ID
exports.getById = async (req, res, next) => {
  try {
    const factura = await prisma.factura.findUnique({
      where: { id: Number(req.params.id) },
    });
    if (!factura) {
      return res.status(404).json({ error: 'Factura no encontrada' });
    }
    res.json(factura);
  } catch (error) {
    next(error);
  }
};

// Crear una nueva factura
exports.create = async (req, res, next) => {
  try {
    const nuevaFactura = await prisma.factura.create({
      data: req.body,
    });
    res.status(201).json(nuevaFactura);
  } catch (error) {
    next(error);
  }
};

// Actualizar una factura
exports.update = async (req, res, next) => {
  try {
    const facturaActualizada = await prisma.factura.update({
      where: { id: Number(req.params.id) },
      data: req.body,
    });
    res.json(facturaActualizada);
  } catch (error) {
    if (error.code === 'P2025') {
      return res.status(404).json({ error: 'Factura no encontrada' });
    }
    next(error);
  }
};

// Eliminar una factura
exports.delete = async (req, res, next) => {
  try {
    await prisma.factura.delete({
      where: { id: Number(req.params.id) },
    });
    res.status(204).send();
  } catch (error) {
    if (error.code === 'P2025') {
      return res.status(404).json({ error: 'Factura no encontrada' });
    }
    next(error);
  }
};
