// Generated by Copilot
const puppeteer = require('puppeteer');

/**
 * Toma una captura de pantalla de una URL.
 * @param {string} url - URL a capturar.
 * @param {string} path - Ruta donde guardar la imagen.
 * @param {object} [options] - Opciones adicionales de Puppeteer.
 * @returns {Promise<void>}
 */
async function screenshot(url, path, options = {}) {
  let browser;
  try {
    browser = await puppeteer.launch(options);
    const page = await browser.newPage();
    await page.goto(url, { waitUntil: 'networkidle2' });
    await page.screenshot({ path });
  } catch (error) {
    console.error('Error al tomar la captura de pantalla:', error);
    throw error;
  } finally {
    if (browser) await browser.close();
  }
}

module.exports = { screenshot };
