// Generated by Copilot
import { Request, Response } from 'express';

export class InvoiceController {
  async getInvoices(req: Request, res: Response): Promise<void> {
    try {
      res.json({ message: 'Obtener facturas' });
    } catch (error) {
      res.status(500).json({ error: 'Error interno del servidor' });
    }
  }
}
