name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Añadir DATABASE_URL para asegurarnos de que Prisma puede generar el cliente
      - name: Setup environment
        run: |
          echo "DATABASE_URL=file:./dev.db" >> $GITHUB_ENV

      - name: Generate Prisma client
        run: npx prisma generate

      # Verifica que el cliente de Prisma se haya generado correctamente
      - name: Verify Prisma client generation
        run: |
          if [ ! -d "node_modules/.prisma/client" ]; then
            echo "Prisma client not found!"
            exit 1
          fi

      # Crear una base de datos SQLite para testing
      - name: Setup database
        run: |
          npx prisma migrate deploy
        env:
          DATABASE_URL: file:./dev.db

      - name: Seed database
        run: npx prisma db seed
        env:
          DATABASE_URL: file:./dev.db

      - name: Run lint
        run: npm run lint
        continue-on-error: true

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Test unitarios
        run: npm run test

      - name: Run E2E tests
        run: npm run test:e2e
        continue-on-error: true